-- ============================================================================
-- Migration: Create Notes Table
-- ============================================================================
-- This is the core table for the Homelab Notebook application.
-- Notes are the primary content type, supporting three modes:
-- - research: External resources, links, articles
-- - project: Active work logs, observations, checklists
-- - reference: Distilled tutorials, step-by-step guides
--
-- Design Decisions:
-- 1. UUID for id: Better for distributed systems, no sequential leaks
-- 2. user_id links to auth.users: Supabase's built-in auth
-- 3. mode as enum: Type safety, prevents invalid values
-- 4. Separate created_at/updated_at: Track creation vs modification
-- 5. content as TEXT: No arbitrary length limits for markdown
-- ============================================================================

-- Create enum for note modes
-- Using an enum ensures only valid modes can be stored
CREATE TYPE note_mode AS ENUM ('research', 'project', 'reference');

-- Create the notes table
CREATE TABLE notes (
    -- Primary key: UUID generated by default
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Foreign key to Supabase auth.users
    -- NOT NULL ensures every note has an owner
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

    -- Note content
    title TEXT NOT NULL,
    content TEXT, -- Nullable: notes can start empty

    -- Note mode (research, project, reference)
    mode note_mode NOT NULL DEFAULT 'project',

    -- Optional: For project mode, link to parent project
    -- This will be populated once we create the projects table
    -- project_id UUID REFERENCES projects(id) ON DELETE SET NULL,

    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Soft delete support (optional, can be added later)
    -- deleted_at TIMESTAMPTZ

    -- Constraints
    CONSTRAINT title_not_empty CHECK (char_length(trim(title)) > 0)
);

-- Create index on user_id for faster queries
-- Most queries will filter by user_id first
CREATE INDEX idx_notes_user_id ON notes(user_id);

-- Create index on mode for filtering by note type
CREATE INDEX idx_notes_mode ON notes(mode);

-- Create index on created_at for sorting
CREATE INDEX idx_notes_created_at ON notes(created_at DESC);

-- Create composite index for common query pattern: user's notes by mode
CREATE INDEX idx_notes_user_mode ON notes(user_id, mode);

-- ============================================================================
-- Full-Text Search Setup
-- ============================================================================
-- PostgreSQL's built-in full-text search is powerful and sufficient for v1.
-- We create a generated column that combines title and content for searching.

-- Add a tsvector column for full-text search
-- 'english' is the text search configuration (handles stemming, stop words)
ALTER TABLE notes ADD COLUMN search_vector tsvector
    GENERATED ALWAYS AS (
        setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(content, '')), 'B')
    ) STORED;

-- Create GIN index for fast full-text search
-- GIN (Generalized Inverted Index) is optimized for tsvector searches
CREATE INDEX idx_notes_search ON notes USING GIN(search_vector);

-- ============================================================================
-- Trigger for updated_at
-- ============================================================================
-- Automatically update updated_at when the row is modified

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER notes_updated_at
    BEFORE UPDATE ON notes
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- Comments for documentation
-- ============================================================================
COMMENT ON TABLE notes IS 'Core content table for Research, Project, and Reference notes';
COMMENT ON COLUMN notes.mode IS 'Note type: research (external resources), project (active work), reference (tutorials)';
COMMENT ON COLUMN notes.search_vector IS 'Generated column for full-text search (title weighted higher than content)';
